### ISSUE TITLE
Implement libsharp spherical harmonic transform 

### ISSUE THREAD

**Issue by jasonmcewen** [astro-informatics/uber3d#3]
Make new class that inherits sht and implement forward and back

Instance of class should be in healpix_sampling

**Comment by elsner** [comment]
//-----------------------------------------------------------------------
// alm to map, temperature only
//-----------------------------------------------------------------------

void alm2map(double\* map, complex double\* alm, double\* w8rings,
             int nside, int lmax, int mmax)

//-----------------------------------------------------------------------

{

  int                                                       spin_t;
  int                                                       ntrans;
  int                                                       stride_pix;
  int                                                       stride_alm;
  sharp_jobtype                                             job;
  sharp_alm_info\*                                           alm_info;
  sharp_geom_info\*                                          geom_info;

  job        = SHARP_ALM2MAP;
  spin_t     = 0;
  ntrans     = 1;
  stride_pix = 1;
  stride_alm = 1;

  CHECK_STACK_ALIGN(8);

  sharp_make_weighted_healpix_geom_info(nside, stride_pix, w8rings,
                                        &geom_info);
  sharp_make_triangular_alm_info(lmax, mmax, stride_alm, &alm_info);

  sharp_execute(job, spin_t, &alm, &map, geom_info, alm_info,
                ntrans, SHARP_DP, NULL, NULL);

  sharp_destroy_geom_info(geom_info);
  sharp_destroy_alm_info(alm_info);

};

//-----------------------------------------------------------------------

//-----------------------------------------------------------------------
// map to alm, temperature only
//-----------------------------------------------------------------------

void map2alm(complex double\* alm, double\* map, double\* w8rings,
             int nside, int lmax, int mmax)

//-----------------------------------------------------------------------

{

  int                                                       spin_t;
  int                                                       ntrans;
  int                                                       stride_pix;
  int                                                       stride_alm;
  sharp_jobtype                                             job;
  sharp_alm_info\*                                           alm_info;
  sharp_geom_info\*                                          geom_info;

  job        = SHARP_MAP2ALM;
  spin_t     = 0;
  ntrans     = 1;
  stride_pix = 1;
  stride_alm = 1;

  CHECK_STACK_ALIGN(8);

  sharp_make_weighted_healpix_geom_info(nside, stride_pix, w8rings,
                                        &geom_info);
  sharp_make_triangular_alm_info(lmax, mmax, stride_alm, &alm_info);

  sharp_execute(job, spin_t, &alm, &map, geom_info, alm_info,
                ntrans, SHARP_DP, NULL, NULL);

  sharp_destroy_geom_info(geom_info);
  sharp_destroy_alm_info(alm_info);

};

**Comment by EiffL** [comment]
Implemented this code using the cxx interface of libsharp on branch #3

**Comment by EiffL** [comment]
Fixed by pull request #16
