### ISSUE TITLE
Perform spherical harmonic transforms over shells

### ISSUE THREAD

**Issue by jasonmcewen** [astro-informatics/uber3d#6]

**Comment by tdk111** [comment]
add loop over spherical shells e.g. to this bit 

template <typename T1, typename T2>
  void foward (uber3d::map<T1> in_map, uber3d::sfb_coefficients<T2> out_almn)
  {
  }

**Comment by EiffL** [comment]
@jasonmcewen @tdk111 I'm assigning myself to this issue and I have created branch #6 to work on it

**Comment by EiffL** [comment]
I ran into troubles with the version of  libsharp included in repository but  I fixed it in #13 and I implemented an new class called sharp_sht, which implements the  sht interface  and can be generated  by the method build_sht of the healpix_sampling class

**Comment by EiffL** [comment]
Fixed by #15
